### PR TITLE
fix: update to pihole 5.1 api for lists

### PR DESCRIPTION
**Pull request by andrewthetechie**
https://github.com/pi-hole/AdminLTE/pull/1387 changes the API endpoints for
list management.

This updates the list and add methods to use the new api
endpoints for v5.1

### CODE REVIEW

**Comment by andrewthetechie** [comment]
@Ewpratten not sure if you're still actively working on this project. Figured I'd pr my fixes from my branch over :)

**Comment by Ewpratten** [comment]
So far, the upstream api has been stable enough that I rarely need to update this library. When an update is needed, people like you tend to open a PR before I get around to implementing the update myself, so thank you, I'll run a quick test, then merge

**Comment by andrewthetechie** [comment]
@Ewpratten sounds good! Glad I did a PR then :)

There's a major API update coming with v6, a complete rewrite.

**Comment by Ewpratten** [comment]
That sounds like a good time to update this library to something newer than python 3.5

I'll look into it

**Pull request merged**
